apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml

images:
  - name: vortexvision/api
    newTag: "1.0.0"
  - name: vortexvision/detector
    newTag: "1.0.0"
  - name: vortexvision/frontend
    newTag: "1.0.0"
  - name: vortexvision/vlm
    newTag: "1.0.0"
