apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - redis-deployment.yaml
  - postgres-deployment.yaml
  - mlflow-deployment.yaml
  - vlm-deployment.yaml
  - api-deployment.yaml
  - detector-deployment.yaml
  - frontend-deployment.yaml
  - kserve-inferenceservice.yaml
  - hpa.yaml
  - ingress.yaml
  - network-policy.yaml
  - pdb.yaml
  - service-monitor.yaml
