apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: vortexvision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: vortexvision
            - name: POSTGRES_USER
              value: vortex
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vortexvision-secrets
                  key: db-password
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: vortexvision-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: vortexvision
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
