apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vortexvision-models-pvc
  namespace: vortexvision
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc   # Use EFS on AWS for ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vortexvision-clips-pvc
  namespace: vortexvision
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vortexvision-db-pvc
  namespace: vortexvision
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
